# Use an official Python runtime as a parent image
FROM python:3.10-slim-buster

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PORT=8080 \
    MESSAGE="Hola Mundo"

# Create and set the working directory
WORKDIR /app

# Copy the requirements file first for caching purposes
COPY requirements.txt .

# Install virtualenv and create a virtual environment
RUN pip install --no-cache-dir virtualenv \
    && virtualenv myenv \
    && . myenv/bin/activate

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application files
COPY . .

# Expose port 8080 to the outside world
EXPOSE 8080

# Define the entry point of the container
ENTRYPOINT ["python"]

# Define the default command to run
CMD ["app.py"]
